spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hh22
    username: root
    password:
  jpa:
    show-sql:
      true
  liquibase:
    change-log: classpath:liquibase-changeLog.xml