spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hh22
    username: postgres
    password:
  jpa:
    show-sql:
      true
    hibernate:
        ddl-auto: create-drop
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:liquibase-changeLog.xml